AllCops:
  RunRailsCops: true
  Exclude:
   - 'db/schema.rb'
   - 'bin/**/*'

Metrics/ClassLength:
  Max: 100

Metrics/LineLength:
  Max: 200

Metrics/MethodLength:
  Max: 50

Metrics/AbcSize:
  Max: 20
  Exclude:
   - 'db/migrate/*'

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/PerceivedComplexity:
  Max: 10

Style/Documentation:
  Enabled: true

Style/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Rails/Output:
  Exclude:
   - 'db/seeds.rb'
   - 'db/seeds/development.rb'
